spring:
  main:
    banner-mode: off
 
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl        
    
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/PuntosWifi
    username: admin
    password: admin
    
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

server:  
  port: 8080